lib/mina/default.rb
As `mina console` simplifies opening a Rails console on server, `mina ssh` can simplify connecting to server itself, without need to remember user and server address.
=> Added `mina ssh` command to connect to server

lib/mina/rails.rb
I'm not sure this is the right approach to solve the issue I run into it. Before executing the console task I need to load chruby (I guess using rvm or rbenv would present similar use case) and I've added the following to my `config/deploy.rb`:
```ruby
task :console => :environment do
end
```
That looks like an ugly workaround to me. Is the suggested code a good approach or is there another way to solve this problem I'm missing?
thank you for working on this project.
=> Make rails console task dependent on the environment

Readme.md, lib/mina/default.rb, lib/mina/ssh_helpers.rb
Users may specify environment variables, as a string, to be passed to the ssh commands.  
Idea: Our app is ported from a heroku environment.  To use nina effectively, in the 12-factor-app paradigm, we need to be able to pass values at deploy time.
```ruby
set :env_vars, "foo=1 bar=baz"
set :env_vars, { File.open(".env").readlines.map(&:chomp).join(" ") }
````
=> Adding support for server environment variables in deploy.rb, (:env_vars)

Readme.md, lib/mina/npm.rb
I simply love the work in __Mina__ thus wanted to use it for deploying nodejs apps.
Thus I ended up writing some tasks that could be useful to others.
Let me know if this is too weird to integrate into a ruby tool.
Cheers!
=> Add npm support with a simple npm:install task

lib/mina/helpers.rb
It is more common to want to specify a custom message than manage custom error levels.
=> Reorder die parameters

lib/mina/rails.rb
If you have a custom location of Rails in your repository, you are now
able to specify the location of the public/assets folder - for example,
'rails/public/assets'.
Without this, when the script to check for the asset differences runs
(`check_for_changes_script`), and this path is wrong, the check to see
if this path exists will fail.
Most of the rest of the variables seem to be able to be customised if
they are non-default, adding this allows for the everything to be.
=> Ability to customise Rails' public assets path

lib/mina/local_helpers.rb, spec/helpers/local_helper_spec.rb
The issue this PR tries to solve is better explained in #309.
Feedback is appreciated, specially regarding tests. I didn't test `Mina::LocalHelpers#local` because I didn't know how to setup the rake scope accordingly. Also I didn't test the return value when `term_mode == :exec` because, well... `Kernel.exec` doesn't return.
=> Fix for #309

lib/mina/git.rb, spec/commands/real_deploy_spec.rb
I did not find a proper way of knowing which version is deployed to my servers.
With this, I can have this task in my `config/deploy.rb`:
```
task :revision do
queue "cat #{deploy_to}/current/.mina_git_revision"
end
```
Maybe this info was stored somewhere, but i have not been able to find it.
Thanks a lot for mina, this is a huge improvement over older deploy plattforms!!!!
=> Save deployed git sha in deploy/current/.mina_git_revision

data/deploy.sh.erb
Hi, I just got started to use mina today. And I noticed that even if some command when deploying exits with a non-zero status, the following commands would still execute. I really don't want that to happen since I simply don't want to know what would happen in that situation.
This patch makes use of bash's `-e` option and bail out asap if any command goes bad. Jenkins CI uses this. And I think deploying scripts are even more critical than CI scripts.
Hope it gets merged :)
=> Use `set -e` to fail fast

data/deploy.sh.erb, spec/commands/deploy_spec.rb, spec/commands/real_deploy_spec.rb, test_env/config/deploy.rb
Add a ':build' step that can be executed after the deployment has been
done and the code moved to its final destination but before the sysmlink
for the current release has been updated (aka new code is live).
This allows for build steps that require code to be in its final
destination (i.e. some autoloaders resolve full paths, moving the code
after the autoloader has done its setup work breaks the code).
=> Allow for a build step

lib/mina/rails.rb
Hi,
The `check_for_changes_script` method don't treat diff to new files. I try use this rake to skip rails seed created by @m3nd3s.
```ruby
desc "Seeding data to Database."
task :'db_seed' do
seed_files = Dir['db/seeds/*.rb']
seed_files.push("db/seeds.rb")
queue check_for_changes_script({
check: 'db/seeds.rb',
at: seed_files,
skip: %[
echo "-----> DB seed unchanged; skipping DB seed"
],
changed: %[
echo "-----> Seeding database"
#{echo_cmd %[#{rake} db:seed]}
],
default: %[
echo "-----> Seeding database"
#{echo_cmd %[#{rake} db:seed]}
]
})
end
```
Then, using -N param in diff command for treat absent files as empty. :smile:
=> Treat absent files as empty when changes script

lib/mina/whenever.rb
I ran into a problem where mina deployments were creating multiple crontab entries.
This was caused because our project's schedule.rb file sets the :domain key *after* requiring 'mina/whenever'.  The code as written was using set_default to set the :whenever_name key at require time.  
I refactored the code to use a lambda which uses the :whenever_name key if defined, otherwise it sets the name to the default name.  This fixes the bug because it is evaluated at runtime, so our :domain key is picked up as defined.  It will also still work with if there is a user-defined :whenever_name variable.
=> Fixed bug where the whenever_name was not getting set properly, causing multiple crontab entries.

data/deploy.rb
After merging #263 I realize that ```$repo``` variable is not present anymore and ```mina setup``` fail.
Here is a fix. 
In addition:
- all sed's magick replaced by Ruby regexps
- a small check for ssh-key existence have been added
It's also possible to fix previous bash version like that:
```ruby
if repository
queue %[
repo="#{repository}" &&
repo_host=`echo $repo | sed -e 's/.*@//g' -e 's/:.*//g'` &&
repo_port=`echo $repo | grep -o ':[0-9]*' | sed -e 's/://g'` &&
if [ -z "${repo_port}" ]; then repo_port=22; fi &&
if ! ssh-keygen -H  -F $repo_host &>/dev/null; then
ssh-keyscan -t rsa -p $repo_port -H $repo_host >> ~/.ssh/known_hosts
fi
]
end
```
but personally I prefer Ruby :)
Regexp have been tested against following repo strings:
```
git@private1.server.com:1111:tmp/repo.git …
```
=> fix missing shell repo variable in setup

0.1.2/about_deploy_rb.html, about_deploy_rb.html
This fixes the actual broken link, but:
There's some reference to `the_command_queue` instead of `command_queue` in `javascripts/search_index.js`, and I don't know how to generate that file. I ended up at ProScribe after a bit of googling but I seem to need a Scribefile for the generation?
=> fix broken command_queue link

mina.gemspec
Rubygems.org reads the license field to show the license on the page and to determine the license when the API is queried. It is important that this field is set for tasks such as automating the building of packages.
=> Add license to gemspec

docs/getting_started.md
Add Rbenv and RVM notes into Getting_started Doc.
I deploy my project with Mina step by step according to the document 'getting_started.md', then I encountered an error:
```
bash: line 82 bundle: command not found
```
At last, I found this is caused by my Rbenv environment, I didn't take note of the some comment in **deploy.rb**
```
...
require 'mina/bundler'
require 'mina/rails'
require 'mina/git'
...
```
``` ruby
...
task :environment do
end
...
```
The Ruby Version Tool(Rbenv or RVM) should be used by most people, so, we may add some notes into the Doc 'getting_started.md' to remind user!
=> add Rbenv and RVM notes

tasks/mina/rbenv.rb
I put the rbenv:load call in my deploy.rb inside an in_path call like so:
```ruby
task :environment do
in_path(fetch(:deploy_to)) do
invoke :'rbenv:load'
end
end
```
This caused a zsh parse error (and I'm assuming bash would have the same problem) because the shell script came out as:
```bash
(cd /deploy/path/current && echo "-----> Loading rbenv" && export RBENV_ROOT='$HOME/.rbenv' && export PATH='$HOME/.rbenv/bin:$PATH' &&  (
if ! which rbenv >/dev/null; then
echo "! rbenv not found"
echo "! If rbenv is installed, check your :rbenv_path setting."
exit 1
fi )
&& eval "$(rbenv init -)")
```
=> fix issues with rbenv:load

data/deploy.rb
I attempted setting up mina today using the latest master (738a8b27ee7c) and I ran into a problem. When I ran `mina setup`, there was an infinite loop of fetch calls. I modified my config/deploy.rb to fix the issue in this way. I suppose I could have posted this as an issue.
=> fix infinite loop in suggested default config

data/deploy.rb, docs/writing_your_own_tasks.md, lib/mina/dsl.rb
Fixes #295 by stealing the code
I don't think this code is ideal as-is. In particular, I'm not 100% sure where the helper should live, and I don't know if it should be included in the default deploy script.
Also, if there is a way to move it from the main deploy task to a before hook, that would be ideal, but I haven't gotten mina 1.x working yet myself so I'm not sure how before hooks work.
=> ensure git pushed function - code props to @fgarcia

tasks/mina/rails.rb
This change fixes a bug that prevents me from using `mina rake`:
```
uniqueway-devin:uniqueway devin$ mina rake[oneoff:test_task]
mina aborted!
NoMethodError: undefined method `deploy_to!' for main:Object
Did you mean?  deploy
/Users/devin/.rvm/gems/ruby-2.3.0/gems/mina-1.0.0.beta5/tasks/mina/rails.rb:97:in `block (2 levels) in <top (required)>'
/Users/devin/.rvm/gems/ruby-2.3.0/gems/mina-1.0.0.beta5/lib/mina/application.rb:16:in `run'
/Users/devin/.rvm/gems/ruby-2.3.0/gems/mina-1.0.0.beta5/bin/mina:4:in `<top (required)>'
/Users/devin/.rvm/gems/ruby-2.3.0/bin/mina:23:in `load'
/Users/devin/.rvm/gems/ruby-2.3.0/bin/mina:23:in `<main>'
```
=> fix mina rake bug

data/deploy.rb
'config/' is not a good example for 'shared_dirs' because in a Rails app this contains many static project files - you would never link the whole folder to 'shared/config'.
=> Improved shared_dirs example + Fix typo in deploy.rb

tasks/mina/deploy.rb
:shared_files like database.yml / secrets.yml are often checked in the repo for development and should be overwritten by the link to the shared file under mina deployment.
=> Allow to overwrite existing :shared_files with the symlink to shared (fixes #452)

data/deploy.rb
Another PR. This time with the link to the Github docs.
https://github.com/mina-deploy/mina/pull/462#issuecomment-254912878
=> fix mina deploy link

docs/migrating.md
This helps migrate without forgetting to add `vendor/bundle` or `public/assets`.
=> Documentation: Migrating shared paths example

spec/support/outputs/rails_assets_clean.txt, spec/support/outputs/rails_db_schema_load.txt, spec/tasks/rails_spec.rb, tasks/mina/rails.rb
We are frequently using these commands in our projects, though adding them to the main would be useful.
* `schema:load` for the initial setup
* `assets:clean` to make sure that we don't end up taking space.
=> rails commands - assets:clean and schema:load 

lib/mina/application.rb
Not all sites using Mina use Rails, and thus don't always have a config folder in root directory, and would like to keep environment and deploy files in root.
=> Allow use of Minafile or deploy.rb outside of config directory

data/deploy.rb
This helps against a hanging connection because it is waiting for `continue with installation? (y/N)`.
```
rbenv: /home/sunny/.rbenv/versions/2.3.0 already exists
^C
-----> Mina: SIGINT received.
Shared connection to example.com closed.
continue with installation? (y/N)
!     Run Error
```
=> Add skip-existing option to example rbenv install

data/deploy.rb
After running `mina init` generated `deploy.rb` has `environment` instead of `remote_environment` on line `31`.
=> Remote environment in deploy example

lib/mina/commands.rb
This fixes a bug where there is no shared paths, but mina still generates &&
=> Fix empty stage queue

lib/mina/helpers/internal.rb, tasks/mina/deploy.rb
Currently, `deploy_script` is overwritable but it's forced under `Mina.root_path` which points the root of this gem.
This causes the option meaningless.
I moved calling `Mina.root_path` not from deploy_script setter but from the option value.
Now user can easily use their on deploy_script.
=> allow user to overwrite deploy_script

docs/default_plugins.md, lib/mina/helpers/internal.rb, spec/lib/mina/helpers/internal_spec.rb, tasks/mina/deploy.rb
In order to use a custom deploy script, we need to monkey patch `Mina::Helpers::Internal` to set a custom path once `Mina::Helpers::Internal#deploy_script` has a hardcoded `Mina.root_path` in it.
This PR allows you to truly use a custom `deploy_script` by doing:
```ruby
set :deploy_script, "/path/to/custom/script"
```
=> Allow setting a custom deploy script

docs/default_plugins.md
Change 'mina/bunlder' for 'mina/bundler'
=> Fix minor typo in documentation

.github/workflows/ci.yml
Set up a GA workflow for running RSpec test suite.
The suite runs on all combinations of:
- OS: MacOS 10.15 and Ubuntu 20.04
- Ruby: 2.6, 2.7 and 3.0
Windows is excluded for now until the issues are fixed (see https://github.com/mina-deploy/mina/issues/660).
=> Test suite CI

spec/support/outputs/git_ensure_pushed.txt, spec/tasks/git_spec.rb, tasks/mina/git.rb
Fixes #639
If a branch doesn't exist either locally or remotely when `git:ensure_pushed` is invoked, `git log` fails with a weird message (`ambiguous argument 'remote/branch': unknown revision or path not in the working tree`). This fix first checks if the branch exists locally and remotely, then compares it.
=> Ensure branch exists locally and remotely before comparing it

spec/lib/mina/runner/exec_spec.rb, spec/lib/mina/runner/printer_spec.rb, spec/lib/mina/runner/system_spec.rb, spec/spec_helper.rb
Adds tests for exec, system and printer runners (skipping pretty for now).
=> Runner tests

.github/workflows/ci.yml, docs/how_mina_works.md, lib/mina.rb, lib/mina/runner/pretty.rb, mina.gemspec, spec/lib/mina/runner/pretty_spec.rb
Replaces open4 with open3 to remove dependency on an external gem. With this fix the error `NotImplementedError: fork is not available on this platform` is fixed on jruby, so we can support that version of Ruby too (I tested this also by building the gem and trying it out on a project with jruby, it works.).
=> Refactor pretty printer

lib/mina/application.rb, spec/lib/mina/application_spec.rb
Adds tests for application class, mainly what happens when you set a command-line option.
=> Application tests

.github/workflows/ci.yml
We only need to run tests when code changes.
=> Exclude documentation from CI workflow

.rspec, spec/lib/mina/commands_spec.rb, spec/lib/mina/configuration_spec.rb, spec/tasks/default_spec.rb, spec/tasks/init_spec.rb
Adds tests for output (so it doesn't go to stdout) and suppresses output where necessary.
=> Prevent stdout output in tests

tasks/mina/default.rb
Otherwise when running `mina -d` you will see lines such as:
```ruby
------- Printing current config variables -------
:debug_configuration_variables => true
:port => 22
:releases_path => #<Proc:0x0000560ef3acbd38...
```
=> Resolve callables when printing debug_configuration

.github/workflows/ci.yml
Adds Ruby 3.1 to test matrix. Removes CI trigger on PR (`push` is enough). Fixes testing against Ruby 3.0 by passing the version as a string (https://github.com/actions/runner/issues/849).
=> Test against Ruby 3.1

lib/mina/runner.rb, spec/lib/mina/runner_spec.rb
PR #686 refactored the Pretty printer to use the Windows-compatible open3 gem instead of the incompatible open4. This PR removes the guard which prevented users from using the Pretty printer on Windows.
Side note: I don't think this guard ever worked because `Gem::Platform.local.os` won't return `:windows` but `cygwin`, `mswin` or something else.
=> Enable Pretty runner on Windows

spec/support/outputs/debug_configuration_variables.txt, spec/tasks/default_spec.rb, tasks/mina/default.rb
Fixes `debug_configuration_variables` task by using `fetch` to resolve the value instead of displaying the raw value from the hash. The previous approach had an issue where when you would override a variable from `config/deploy.rb` with an environment variable, the task would still display the value set in `config/deploy.rb`. This PR also introduces some minor aesthetic changes in the output.
=> Print correct values in `debug_configuration_variables` task

spec/support/outputs/ssh.txt, spec/tasks/default_spec.rb, tasks/mina/default.rb
Refactors `ssh` task to use Mina DSL.
This fixes part of https://github.com/mina-deploy/mina/issues/660 (2nd issue) as the command will now be properly escaped.
=> Fix `ssh` task escaping

spec/support/outputs/bundle_clean.txt, tasks/mina/bundler.rb
Fixes https://github.com/mina-deploy/mina/issues/521.
Removes interpolation of `:bundle_options` variable from the `bundle clean` command as those options cannot be used in that command.
=> Remove :bundle_options from bundle clean

data/deploy.rb, docs/getting_started.md, tasks/mina/chruby.rb, tasks/mina/rbenv.rb, tasks/mina/rvm.rb, tasks/mina/ry.rb
Reverts https://github.com/mina-deploy/mina/pull/709 until a decision is made whether we'll indeed go forward with removing these tasks from the main gem.
=> Revert "Deprecate version manager tasks"
